#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);


my $event = 'ocs-update';
templates2events("/etc/httpd/conf/httpd.conf", $event);
templates2events("/etc/php.ini", $event);
templates2events("/etc/my.cnf", $event);
templates2events("/etc/ocsinventory/ocsinventory-reports/dbconfig.inc.php", qw(ocs-update bootstrap-console-save));
templates2events("/etc/e-smith/sql/init/80ocs_mysql.sql", $event);

event_link("ocs-conf", $event, "10");
event_link("ocs-conf", "domain-modify", "10");
event_link("ocs-conf", "bootstrap-console-save", "10");
event_link("ocs-load-mysqldump-conf", $event, "91");
event_link("ocs-load-mysqldump-conf", "bootstrap-console-save", "91");

safe_symlink("start", "root/etc/e-smith/events/$event/services2adjust/mysql.init");
safe_symlink("sigusr1", "root/etc/e-smith/events/$event/services2adjust/httpd-e-smith");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/mysqld");

safe_symlink("/etc/e-smith/templates-default/template-begin-php", "root/etc/e-smith/templates/etc/ocsinventory/ocsinventory-reports/dbconfig.inc.php/template-begin");

panel_link("ocs", 'manager');


